apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ops-user-full-access-binding
roleRef:
  kind: ClusterRole
  name: ops-user-full-access
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: c007d29b-e404-4b54-b37e-c2ca955f38ac # groupObjectId
  apiGroup: rbac.authorization.k8s.io